---

- name: Test ping host all
  hosts: main_server
  #become: yes
  gather_facts: yes

  tasks:

  - name: COPY SRC to host
    include_role:
      name: create_user
      tasks_from: main
    vars:
      user_name: '{{ item }}'
      generate_ssh_key: no
    loop: '{{user_list}}'

- name: Test ping host all2

  hosts: corp_servers
  #become: yes
  gather_facts: yes

  tasks:

  - name: COPY SRC to host
    include_role:
      name: create_user
      tasks_from: —Åreate_users_copy_ssh
    vars:
      user_name: '{{ item }}'
      generate_ssh_key: no
    loop: '{{user_list}}'
