---
- name: create /opt/ansible
  file:
    path: /opt/ansible
    state: absent
    force: yes

- name: create /opt/ansible
  file:
    path: /opt/ansible
    state: directory

# - name: "create /opt/ansible/{{user_name}}"
#   file:
#     path: /opt/ansible
#     state: directory

- name: "create /opt/ansible/{{ user_name}}.yml"
  file:
    path: /opt/ansible/{{ user_name}}.yml
    state: touch

- name: "create /opt/ansible/{{ user_name}}_key.yml"
  file:
    path: /opt/ansible/{{ user_name}}_key.yml
    state: touch


- set_fact:
    my_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- debug:
    msg: "{{ user_name}}: {{ my_pass }}"



- name: Add user to users.yml
  lineinfile:
    path: '/opt/ansible/{{ user_name }}.yml'
    line: "{{ my_pass}}"

- name: Ensure group "somegroup" exists
  group:
    name: devops
    state: present

#- name: Ansible date timestamp example
#  debug:
    #msg: "{{ '%Y-%m-%d' | strftime( ( ansible_date_time.epoch | int ) + ( 86400 * 3 )  ) }}"
- set_fact:
    expire_epoch: "{{ ansible_date_time.epoch | int +86400}}"
- name: Ansible date timestamp example
  debug:
    var: expire_epoch

- name: Added user to admins
  user:
    expires: '{{ expire_epoch }}'    
    name: '{{ user_name }}'
    password: "{{my_pass | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    generate_ssh_key: '{{generate_ssh_key }}'


- name:  get key
  shell: 'cat /home/{{user_name}}/.ssh/id_rsa.pub'
  register: user_ssh_key


- name:  Add public key  to users.yml
  lineinfile:
    path: "/opt/ansible/{{ user_name }}_key.yml"
    line: "{{ user_ssh_key.stdout }}"
  when: generate_ssh_key

- name: COPY
  fetch:
    src: /opt/ansible/{{ user_name }}.yml
    dest: '{{ workspace}}/{{ user_name }}.yml'
    flat: yes

- name: COPY2
  fetch:
    src: /opt/ansible/{{ user_name }}_key.yml
    dest: '{{ workspace}}/{{ user_name }}_key.yml'
    flat: yes
  when: generate_ssh_key


      # expires: 1422403387
      # - name: Download foo.conf

# - name: Test ping host all
#   hosts: main_server
#   #become: yes
#   gather_facts: yes
# corp_servers
  # NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
  # - name: Validate the sudoers file before saving
  #   ansible.builtin.lineinfile:
  #     path: /etc/sudoers
  #     state: present
  #     regexp: '^%ADMIN ALL='
  #     line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
  #     validate: /usr/sbin/visudo -cf %s
       #   get_url:
       # url: "{{ nodejs_url }}"
  #     dest: /opt/node.tar.xz
  #     mode: '0440'
  #
  # - name: tar.xz
  #   ansible.builtin.unarchive:
  #     src: /opt/node.tar.xz
  #     dest: /opt
  #     remote_src: yes
